#!/usr/bin/env python3
"""Machine-owned deterministic entrypoint for john-deere-x9-1100.

Generated by scripts/fleet/build_machine.py. The shared generator remains the
authoring implementation and is hash-bound separately in asset-receipt.json.
"""
from pathlib import Path
import runpy
import sys

HERE = Path(__file__).resolve().parent
SHARED_GENERATOR = (HERE / "../../../../scripts/fleet/build_machine.py").resolve()
DESIGN = (HERE / "../design.json").resolve()
OUTPUT_DIR = (HERE / "../..").resolve()
sys.argv = [str(SHARED_GENERATOR), "--", "--design", str(DESIGN), "--output-dir", str(OUTPUT_DIR)]
runpy.run_path(str(SHARED_GENERATOR), run_name="__main__")
